name: preprocessing
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - numpy=1.26.4
  - pandas=2.2.2
  - jupyter
  - notebook
  - pip
  - pip:
    - numpy<2
    - aniposelib>=0.7.0
    - easydict==1.13
    - einops==0.8.1
    - joblib==1.5.2
    - json5==0.12.1
    - opencv-python-headless==4.9.0.80
    - toml==0.10.2